query PostList {
  posts {
    edges {
      node {
        id
        title
        excerpt
        slug
        featuredImage {
          node {
            id
            mediaItemUrl
            mediaDetails {
              sizes {
                name
                sourceUrl
              }
            }
          }
          
        }
        post_details {
          subtitle
          year
          block{
            image {
              id
              mediaItemUrl
              caption
            }
            text
          }
        }
      }
    }
  }
}